### ISSUE TITLE
Perhaps Flask-Assets should be removed

### ISSUE THREAD

**Issue by holmescn** [JackStouffer/Flask-Foundation#10]
I am looking for flask skeleton that could accelerate the development of flask webpage or webapp. There are two candidate, one is Flask-Foundation, the other is overholt. Both of them use flask-assets for assets bundle. But I think that the frontend tasks should be done with frontend toolchains. So I think that flask-assets should be removed and add npm package.json which contains gulp/webpack or something else.

**Comment by JackStouffer** [comment]
I disagree,

1. This repo is focused on giving people a **Flask** skeleton. I specifically left out things like the database, celery and message queues, migrations, etc.
2. All of those front end tools require running a separate task to mange your scripts/styles while you develop
3. gulp and webpack require the user to install npm and node while WebAssets is entirely Python driven
4. Moving to one of these tools subjects this repo to the "Shiny Thing of the Day" JavaScript syndrome. Did you notice how you didn't mention Grunt? It's because webpack is the new hotness, even though we were told not only a year ago that glup was the second coming. And, next year it will be something else.

There are also a ton of tiny things I don't about any of these tools. I'm sorry, but I'm going to have to say no.

If you don't like WebAssets, then delete `assets.py` and you're good.
